use_frameworks!

platform :ios, '12.0'

target 'AMToast_Example' do
  pod 'AMToast', :path => '../'

  target 'AMToast_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end
end
